name: Checks

on:
  pull_request:
jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world
        run: echo hello world

      - name: Other echo 
        run: echo hello ${{ secrets.SECRET }} world

      - name: Heck
        run: |
          touch i-was-here.txt
          git config --global user.email "nikita.k@lido.fi"
          git config --global user.name "Nikita Kozlov"
          git add .
          git commit -m 'i was here'
          git push origin HEAD:main
